FROM tomcat:9-jdk11-adoptopenjdk-hotspot

ENV JAVA_OPTS="$JAVA_OPTS -Djava.security.egd=file:/dev/urandom"

COPY target/de4a-connector-mock-0.2.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]
