const trans_en = {
    "doTitle": "Data Owner mock",
    "previewTitle": "Preview",
    "explanation": "The following information has been retrieved from the business register. Please review the provided information. \n\n By selecting [Register] you allow this information to be used for the company registration at the procedure. Selecting [Deny] will stop the procedure and the information will not be registered. \n\n  The information is formatted according to the European standards, therefore some information might look different from the country specific presentation. ",
    "canonicalEvidenceFields": {
        "LegalEntity": "Legal entity",
        "CompanyName": "Company name",
        "LegalEntityLegalName": "Legal name",
        "CompanyType": "Company type",
        "CompanyStatus": "Company status",
        "CompanyActivity": "Company activity",
        "ActivityDescription": "Activity description",
        "RegistrationDate": "Registration date",
        "CompanyEUID": "EUID",
        "CompanyContactData": "Contact data",
        "Email": "e-mail",
        "RegisteredAddress": "Registered address",
        "PostalAddress": "Postal address",
        "HigherEducationDiploma": "Higher Education Diploma",
        "identifier": "Identifier",
        "title": "Title",
        "description": "Description",
        "additionalNote" : "Additional note",
        "degree": "Degree",
        "country": "Country",
        "institutionName": "Institution name",
        "studyProgramme": "Study programme",
        "mainFieldOfStudy": "Main field of study",
        "modeOfStudy": "Mode of study",
        "durationOfEducation": "duration of education",
        "scope": "Scope",
        "dateOfIssue": "Date of issue",
        "placeOfIssue": "Place of issue",
        "name": "Name",
        "holderOfAchievement": "Holder of Achievement",
        "nationalId": "National ID",
        "givenNames": "Given names",
        "familyName": "Family names",
        "dateOfBirth": "Date of birth",
        "MarriageEvidence": "Marriage evidence",
        "IssueDate": "Issue date",
        "IssuingAuthority": "Issuing authority",
        "PrefLabel": "Public organization",
        "IssuingPlace": "Issuing place",
        "CertifiesMarriage": "Certifies marriage",
        "DateOfMarriage": "Date of marriage",
        "Spouse": "Spouse",
        "DateOfBirth": "Date of birth",
        "Year": "Year",
        "Month": "Month",
        "Day": "Day",
        "PersonName": "Person name",
        "FamilyName": "Family name",
        "GivenName": "Given name",
        "Identifier": "Identifier",
        "Gender": "Gender",
        "PlaceOfMarriage": "Place of marriage",
        "CertifiesBirth": "Certifies birth",
        "Child": "Child",
        "PlaceOfBirth": "Place of birth",
        "DomicileRegistrationEvidence": "Domicile registration evidence",
        "CertifiesDomicile": "Certifies domicile",
        "Inhabitant": "Inhabitant",
        "Domicile": "Domicile",
        "IdentifierType": "Identifier type",
        "IssuingAuthorityID": "Issuing authority IfirstNameD",
        "Citizenship": "Citizenship",
        "Name": "Name",
        "Parent": "Parent",
        "BirthEvidence": "Birth evidence",
        "FamilyNameAfterMarriage": "Family name after marriage",
        "FamilyNameBeforeMarriage": "Family name before marriage",
        "MaritalStatusBeforeMarriage": "Marital status before marriage",
        "CertifiesEndOfMarriage": "Certifies end of marriage",
        "DateOfEndOfMarriage": "Date of end of marriage",
	    "Cause": "Cause",

		"personIdentifier": "personIdentifier",
		"gender": "gender",
		"firstName": "firstName",
		"currentAddress": "currentAddress",
		"birthName": "birthName",
		"vatRegistration": "vatRegistration",
		"taxReference": "taxReference",
		"sic": "sic",
		"seed": "seed",
		"lei": "lei",
		"legalPersonIdentifier": "legalPersonIdentifier",
		"legalName": "legalName",
		"legalAddress": "legalAddress",
		"eori": "eori",
		"d201217EUIdentifier": "d201217EUIdentifier",
		"canonicalEvidence": "canonicalEvidence",
		"timeStamp": "timeStamp",
		"requestId": "requestId",
		"redirectURL": "redirectURL",
		"agentUrn": "agentUrn",
		"assuranceLevelValue": "assuranceLevelValue",
		"assuranceLevelCodeListVerionID": "assuranceLevelCodeListVerionID",
		"assuranceLevelCodeListID": "assuranceLevelCodeListID",
		"assuranceLevelAgencyName": "assuranceLevelAgencyName",
		"assuranceLevelAgencyID": "assuranceLevelAgencyID",
		"value": "value",
		"latinScript": "latinScript",
		"languageLocaleID": "languageLocaleID",
		"languageID": "languageID",
	 
		"ResponseEventSubscriptionItem" : "Subscription item",
		"RequestItemId" : "Request item identifier",
		"SubscriptionPeriod" : "Subscription period",
		"StartDate" : "Start date",
		"EndDate" : "End date",
		
		"NotificationId": "Notification Id",
		"SpecificationId": "Specification Id",
		"TimeStamp": "TimeStamp",
		"AgentUrn": "Agent Urn",
		"AgentName": "Agent Name",
		"NotificationItemId": "Notification Item Id",
		"EventId": "Event Id",
		"LegalPersonIdentifier": "Legal Person Identifier",
		"LegalName": "Legal Name",
		"PersonIdentifier": "Person Identifier",
		"FirstName": "First Name",
		"CanonicalEventCatalogUri": "Canonical Event Catalog Uri",
		"EventDate": "Event Date",
		
		"averageGrade": "Average Grade",
		"nameOfSchool": "Name of School",
		"grade": "Grade",
		"issuingDate": "Issuing Date",
		"certificateID": "Certificate ID",
		"effectiveDate": "Effective Date",
		"disabilityPercentage": "Disability Percentage"
		
    },
    "acceptButton": "Accept data",
    "rejectButton": "Reject data",
    "legalText": "The DE4A project (https://www.de4a.eu/about-project) has been funded by the European Commission. This project pilots specific procedures of the Single Digital Gateway Regulation - Article 14 of the SDGR specifies the requirement for an explicit request.",
    "previewButton": "Preview",
	"detailButton": "Detail",
    "requestListTitle": "Select an evidence to preview",

	"requestSubscriptionListTitle": "Select a subscription",
	"sendNotification": "Send notification",
	"buildNotification": "Build notification",
	"subscriptionExplanation" : "The following information has been retrieved from the subscription message received. Please review the provided information. By selecting [Send notification] a notification will be sent to the subscribed participant. \n\n  The information is formatted according to the European standards, therefore some information might look different from the country specific presentation. ",
	
	"continue": "Continue"
}

export default trans_en